site:
  title: Open Liberty Docs
  start_page: ROOT::overview.adoc
content:
  sources:
  - url: https://github.com/kinueng/docs.git
    branches: [v22.0.0.1, v22.0.0.2]
  - url: https://github.com/kinueng/docs-generated.git
    branches: [v22.0.0.1, v22.0.0.2]
    
asciidoc:
  attributes:
    icons: font
    source-highlighter: highlightjs
    allow-uri-read: true
  extensions:
    - scripts/ol-asciidoc.js
ui:
  bundle:
    url: src/main/content/antora_ui/build/ui-bundle.zip
    snapshot: true
  default_layout: general-reference
